# Generated by Django 4.2.4 on 2023-09-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="data",
        ),
    ]
